version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb -E production
    environment:
      DB_HOST: db
    volumes:
      - .:/app
      - bundle:/app/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  nginx:
    image: nginx
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
volumes:
  db_data:
    driver: local
  bundle:
    driver: local