version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    environment:
      DB_HOST: db
      HTTP_PROXY: proxy.use.ac.jp:8080
      HTTPS_PROXY: proxy.use.ac.jp:8080
    volumes:
      - .:/app
      - bundle:/app/bundle
    ports:
      - "8080:80"
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data:
    driver: local
  bundle:
    driver: local