FROM ruby:2.4.1

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

ENV APP_ROOT /app
ENV RAILS_ENV production

ENV BUNDLE_JOBS 2
ENV BUNDLE_PATH $APP_ROOT/bundle

WORKDIR $APP_ROOT

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

COPY Gemfile Gemfile.lock ./
RUN gem update bundler && bundle install
COPY . $APP_ROOT

RUN rails assets:precompile

