version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    environment:
      DB_HOST: db
      SECRET_KEY_BASE: 1beb94daef0ea8149b0be324d5978fa4995a152a387df528f1bc92feb2d8bb2116be334d1d96a0201fb596c79f66b58478adec28c8de30d901e593502613b693
    volumes:
      - .:/app
      - bundle:/app/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      DB_HOST: '127.0.0.1'
      DB_NAME: bookmanager_app_db
      DB_USERNAME: 'root'
      DB_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  nginx:
    image: nginx
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
volumes:
  db_data:
    driver: local
  bundle:
    driver: local